# Hyperliquid Trade Following Bot Configuration
# Copy this file to config.toml and fill in your values

# Account address to follow for trades
# Example: The White Whale address (replace with your target)
target_account = "0xb8b9e3097c8b1dddf9c5ea9d48a7ebeaf09d67d2"

# Your Hyperliquid API credentials (not needed for paper trading)
# Get these from https://app.hyperliquid.xyz/API
api_key = "your_api_key_here"
private_key = "your_64_character_hex_private_key_here"

# Minimum trade value to copy (in USD)
# Trades below this threshold will be ignored
copy_threshold = 1000.0

# Paper trading configuration
paper_trading_only = true  # Currently only paper trading is supported

# Data storage directory (relative to PREFIX env var, defaults to "data/hype-copy-bot")
# With PREFIX="/srv" (default), data_dir="data/hype-copy-bot" creates files in /srv/data/hype-copy-bot/
# Use data_dir="trading_data" for /srv/trading_data/
data_dir = "data/hype-copy-bot"

# Bankroll management
# Your starting capital for paper trading (in USD)
bankroll = 10000.0

# Maximum leverage multiplier (1.0 = no leverage, 2.0 = 2x leverage)
# Position size cannot exceed bankroll * leverage
leverage = 3.0

# Base notional amount for each trade (in USD)
# This is the default size for new positions, scaled by available capital
# Actual trade size = min(base_notional, available_capital_percentage * base_notional)
base_notional = 1000.0
